seml:
  # Set seml config

slurm:
  # Set config for slurm

fixed:
  model_path: ""
  skip_existing_experiments: True

grid:
  attack_config:
    control_prompt: 
      type: choice
      options:
        - "! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !"
        - "! ! ! ! !"
        - "!"
    
baseline_universal:
  fixed:
    model_name: "Llama-2-7b-chat-hf" 
    dataset_name: "hp_qa_en"    
    attack_config:
      iters: 100
      step_size: 0.001
      num_tokens_printed: 100
      batch_size: 8
      verbose: True
      early_stopping: False
      generate_interval: 1
      il_gen: "all"
      attack_type: "universal"
  grid:
    test_split: 
      type: choice
      options:
        - 0
        - 0.5
        - 0.75
    
baseline_individual:
  fixed:
    model_name: "Llama-2-7b-chat-hf" 
    dataset_name: "hp_qa_en"    
    attack_config:
      iters: 100
      step_size: 0.001
      num_tokens_printed: 100
      batch_size: 8
      verbose: True
      early_stopping: False
      generate_interval: 1
      il_gen: "all"
      attack_type: "individual"
    test_split: 0
    
no_attack:
  fixed:
    dataset_name: "hp_qa_en"
    attack_config:
      iters: 1
      step_size: 0
      num_tokens_printed: 100
      batch_size: 16
      verbose: True
      early_stopping: False
      generate_interval: 1
      il_gen: "all"
      attack_type: "no_attack"
      control_prompt: None
    test_split: 0
  grid:
    model_name: 
      type: choice
      options:
        - "Llama2-7b-WhoIsHarryPotter" 
        - "Llama-2-7b-chat-hf" 