seml:
  # Set seml config

slurm:
  # Set config for slurm

fixed:
  model_path: ""
  skip_existing_experiments: True

grid:
  model_name: 
    type: choice
    options:
      - "Llama-2-7b-chat-hf"
      - "LlamaGuard-7b"
      - "Mistral-7B-v0.1"
      - "vicuna-7b-v1.5"

baselines:
  fixed:
    dataset_name: "harmful_behaviors"
    attack_config:
      iters: 1
      step_size: 0
      num_tokens_printed: 100
      batch_size: 16
      verbose: True
      early_stopping: False
      attack_type: "no_attack"
      generate_interval: 1
      il_gen: "all"
      control_prompt: None
  grid:
    test_split:
      type: choice
      options:
        - 0
        - 0.5
        - 0.75