seml:
  # Set seml config

slurm:
  # Set config for slurm

fixed:
  model_path: ""
  skip_existing_experiments: True

no_attack:
  fixed:
    dataset_name: "hp_qa_en"
    attack_config:
      iters: 100
      step_size: 0
      num_tokens_printed: 100
      batch_size: 16
      verbose: True
      early_stopping: False
      generate_interval: 1
      il_gen: "None"
      attack_type: "no_attack"
      control_prompt: None
    test_split: 0
  grid:
    model_name: 
      type: choice
      options:
        - "Llama2-7b-WhoIsHarryPotter" 
        - "Llama-2-7b-chat-hf" 
    attack_config:
      temperature: 
        type: choice
        options:
          - 10
          - 2
          - 1
          - 0.5
          - 0.1